### PR TITLE
GPII-2053:  Added transformation functions to handle dates....

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-2053](https://issues.gpii.net/browse/GPII-2053) for details.

### CODE REVIEW

**Comment by amb26** [comment]
Could you please close this and reopen as a pull against Infusion's https://github.com/fluid-project/infusion/blob/master/src/framework/core/js/ModelTransformationTransforms.js - thanks!
Please also include the booleanToString transform

**Comment by the-t-in-rtf** [comment]
Absolutely!  We should discuss a few things first, but totally excited to do that.  I will write up a ticket with the proposed additions, and suggest other useful transform functions I have created.

**Comment by the-t-in-rtf** [comment]
As we discussed, I will port over the rest of the functions in the same file, perhaps renaming objectToString to better reflect its purposes, for example, objectToJSON.

**Comment by the-t-in-rtf** [comment]
Here's [the new PR against infusion](https://github.com/fluid-project/infusion/pull/761).

**Pull request closed without merging**
